### PR TITLE
sqlite file for the o2o unit tests

### PR DESCRIPTION
**Pull request by panoskatsoulis**

### CODE REVIEW

**Comment by panoskatsoulis** [comment]
@qliphy please merge this
it's the required file for the L1O2O unit tests

This is meant to be used for the tests in the following PRs
- https://github.com/cms-sw/cmssw/pull/37601
- https://github.com/cms-sw/cmssw/pull/37602

**Comment by qliphy** [comment]
@panoskatsoulis  Ok, let's wait for the tests done.  https://github.com/cms-sw/cmssw/pull/37601#issuecomment-1107633380

**Comment by tvami** [comment]
assign db

**Comment by tvami** [comment]
+db

**Comment by smuzaffar** [comment]
+externals

**Comment by tvami** [comment]
Hi @perrotta @qliphy seems like the unit test is actually working too
https://github.com/cms-sw/cmssw/pull/37602#issuecomment-1109965317
so please consider merging this external in advance of merging the PR that uses this. Thanks

**Comment by epalencia** [comment]
+l1

**Comment by perrotta** [comment]
+1
- Tested together with #37602

**Pull request merged**
